apiVersion: v1
kind: Namespace
metadata:
  name: postgres-db
---
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disk"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: hammerdb-sut
          operator: In
          values:
          - "database"
  storageClassDevices:
    - storageClassName: "local-sc"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/nvme0n1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: postgres-persistent-storage
    namespace: postgres-db
spec:
    storageClassName: local-sc
    accessModes:
    - ReadWriteOnce
    volumeMode: Filesystem
    resources:
      requests:
        storage: 1024Gi 
