apiVersion: v1
kind: Pod
metadata:
  name: db-vol-inspect
  namespace: postgres-db
spec:
  nodeSelector:
    hammerdb-sut: "database"
  containers:
  - name: db-vol-inspect
    image: registry.redhat.io/ubi8/ubi:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: postgres-persistent-storage
      mountPath: /var/lib/pgsql/data
      readOnly: false
  restartPolicy: Never
  volumes:
  - name: postgres-persistent-storage
    persistentVolumeClaim:
      claimName: postgres-persistent-storage
